#!/bin/bash
# Script to help setup GitHub secrets for deployment

echo "🔐 GitHub Secrets Setup Helper"
echo "=============================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo ""
echo "1. PI_HOST - Your Raspberry Pi hostname or IP address"
echo "   Example: 192.168.1.100 or raspberrypi.local"
echo ""
echo "2. PI_USER - SSH username for Raspberry Pi (usually 'pi')"
echo "   Example: pi"
echo ""
echo "3. PI_PORT - SSH port (default is 22)"
echo "   Example: 22"
echo ""
echo "4. PI_SSH_KEY - Your private SSH key for accessing the Pi"
echo "   To generate: ssh-keygen -t ed25519 -C 'github-actions'"
echo "   Then copy the private key content"
echo ""
echo "5. CONFIG_JSON - Your trading bot configuration (optional)"
echo "   The content of your config/config.json file"
echo ""
echo "6. TELEGRAM_BOT_TOKEN - For deployment notifications (optional)"
echo "   Get from @BotFather on Telegram"
echo ""
echo "7. TELEGRAM_CHAT_ID - Your Telegram chat ID (optional)"
echo "   Get from @userinfobot on Telegram"
echo ""
echo "----------------------------------------"
echo ""
echo "🔑 Generating SSH key pair for GitHub Actions..."
echo ""

# Generate SSH key if it doesn't exist
if [ ! -f ~/.ssh/github_actions_deploy ]; then
    ssh-keygen -t ed25519 -C "github-actions-deploy" -f ~/.ssh/github_actions_deploy -N ""
    echo ""
    echo "✅ SSH key generated!"
    echo ""
else
    echo "⚠️  SSH key already exists at ~/.ssh/github_actions_deploy"
    echo ""
fi

echo "📋 Copy this public key to your Raspberry Pi's ~/.ssh/authorized_keys:"
echo ""
cat ~/.ssh/github_actions_deploy.pub
echo ""
echo "----------------------------------------"
echo ""
echo "📋 Copy this private key to GitHub secret PI_SSH_KEY:"
echo ""
cat ~/.ssh/github_actions_deploy
echo ""
echo "----------------------------------------"
echo ""
echo "🚀 Quick setup commands for your Pi:"
echo ""
echo "ssh $PI_USER@$PI_HOST 'mkdir -p ~/.ssh && echo \"$(cat ~/.ssh/github_actions_deploy.pub)\" >> ~/.ssh/authorized_keys'"
echo ""
echo "----------------------------------------"
echo ""
echo "📝 To add secrets to GitHub:"
echo "1. Go to your repository on GitHub"
echo "2. Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret'"
echo "4. Add each secret listed above"
echo ""
echo "🔗 Direct link (replace with your repo):"
echo "https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo ""