name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            # Update code
            cd ~/trader
            git pull origin main
            
            # Install dependencies
            source venv/bin/activate
            pip install -r requirements-pi.txt
            
            # Restart bot
            sudo systemctl restart trader
            
            echo "✅ Deployed!"