name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean runner workspace
        run: |
          # Clean the runner's workspace to avoid conflicts
          rm -rf ${{ github.workspace }}/*
          
      - name: Deploy to bot directory
        run: |
          echo "🚀 Deploying to pi-trader..."
          
          # Go to the actual bot directory
          cd ~/code/pi-trader
          
          # Save local config
          cp config/config.json config/config.json.backup
          
          # Pull latest changes
          git pull origin main
          
          # Restore local config (with API keys)
          cp config/config.json.backup config/config.json
          rm config/config.json.backup
          
          # Update dependencies
          source venv/bin/activate
          pip install -r requirements-pi.txt
          
          # Restart service
          sudo systemctl restart trader || echo "Service not configured"
          
          echo "✅ Deployed successfully!"
          echo "📊 Check logs: sudo journalctl -u trader -f"