name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            # Update code
            cd ~/code/pi-trader
            git pull origin main
            
            # Create venv if doesn't exist
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            
            # Install dependencies
            source venv/bin/activate
            pip install -r requirements-pi.txt
            
            # Restart bot
            sudo systemctl restart trader || echo "Service not yet configured"
            
            echo "✅ Deployed!"