name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Tu Raspberry Pi!
    steps:
      - uses: actions/checkout@v3
      
      - name: Update code
        run: |
          # Ya estamos en la Pi!
          cd ~/code/pi-trader
          git pull origin main
      
      - name: Install dependencies
        run: |
          cd ~/code/pi-trader
          source venv/bin/activate
          pip install -r requirements-pi.txt
      
      - name: Restart bot
        run: |
          sudo systemctl restart trader || echo "Service not yet configured"
          echo "✅ Deployed locally on Pi!"